changed logic for comparison with reference

diff --git a/.github/workflows/burn_cell_primordial_chem.yml b/.github/workflows/burn_cell_primordial_chem.yml
--- a/.github/workflows/burn_cell_primordial_chem.yml
+++ b/.github/workflows/burn_cell_primordial_chem.yml
@@ -35,4 +35,29 @@ jobs:
       - name: Compare to stored output
         run: |
           cd unit_test/burn_cell_primordial_chem
-          diff -I "^AMReX" -I "^burn_cell_primordial_chem" -I "^Start testing" -I "^End testing" test.out reference_solution.out
+          line_numbers=(456 458 460 463 465 471 476)
+          threshold=100
+
+          error_found=false
+
+          for line_number in "${line_numbers[@]}"; do
+              value1=$(sed -n "${line_number}s/[^0-9]*\([0-9.]*\).*/\1/p" test.out)
+              value2=$(sed -n "${line_number}s/[^0-9]*\([0-9.]*\).*/\1/p" reference_solution.out)
+
+              ratio=$(awk "BEGIN {printf \"%.2f\", $value1 / $value2}")
+
+              if (( $(echo "$ratio > $threshold" | bc -l) )); then
+                 echo "Line number: $line_number"
+                 echo "Value in test.out: $value1"
+                 echo "Value in reference_solution.out: $value2"
+                 echo "Difference: $difference"
+                 echo
+                 error_found=true
+              fi
+          done
+
+          if $error_found; then
+             echo "Errors were found. Exiting with status 1."
+             exit 1
+          fi
+
